project:
  type: website

website:
  title: "Martijn L.G. van Dam"
  navbar:
    left:
      - href: index.qmd
        text: "About me"
      - href: m_resume.pdf
        text: "CV"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



